### ISSUE TITLE
Is the order of neighbours returned by `FindNeighbors` guaranteed?

### ISSUE THREAD

**Issue by shwina** [udacity/CppND-Route-Planning-Project#18] opened 2020-01-13 16:12 UTC
Given that `RouteModel` is using an `unordered_map` underneath, is the order of elements returned by `FindNeighbors` guaranteed?

More specifically, is the order of values used in [this test](https://github.com/udacity/CppND-Route-Planning-Project/blob/master/test/utest_rp_a_star_search.cpp#L79-L80) always expected to be the same?

**Comment by mFontoura** [comment] 2020-01-22 18:21
are you using Windows? I think the issue is related with Visual C++ (in my case). My code works on the workspace machine but not locally when using Visual Studio. So, in my machine I swapped the last two positions of the test vectors start_neighbor_g_vals and start_neighbor_h_vals

**Comment by shwina** [comment] 2020-01-23 00:18
Nope, I'm on a Mac. I believe that as a consequence of the `unordered_map`, the order in which neighbours are returned is dependent on the implementation. That test is not guaranteed to pass on all platforms/compilers.

**Comment by shwina** [comment] 2020-01-26 20:38
Would be great to hear from someone on the @udacity team about this possible bug, as it might lead students to believe they are doing something wrong, while in fact their code might be correct. Thanks for the fantastic work you all are doing :)

**Comment by SudKul** [comment] 2021-02-23 11:11
Thanks, @mFontoura, and other participants, 
The issue has been fixed now, refer #21

**Closed by SudKul** 2021-02-23 11:11 UTC
